
CREATE DATABASE oldmsi CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'oldmsi'@'localhost' IDENTIFIED BY 'oldmsi';
GRANT ALL PRIVILEGES ON *.* TO 'oldmsi'@'localhost' WITH GRANT OPTION;
CREATE USER 'oldmsi'@'%' IDENTIFIED BY 'oldmsi';
GRANT ALL PRIVILEGES ON *.* TO 'oldmsi'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

