/*
 * Copyright 2016 Danish Maritime Authority.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.niord.importer.nm.batch;

import org.niord.core.geojson.GeometryFormatService;
import org.niord.core.message.Message;
import org.niord.core.message.batch.BatchMessageImportReader;
import org.niord.core.message.vo.SystemMessageVo;
import org.niord.importer.nm.extract.NmHtmlExtractor;
import org.niord.model.DataFilter;

import javax.inject.Inject;
import javax.inject.Named;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Imports a list of legacy NM messages from HTML file generated by saving an NM Word document as HTML.
 * <p>
 * Please note, the actual dk-nm-import.xml job file is not placed in the META-INF/batch-jobs of this project,
 * but rather, in the META-INF/batch-jobs folder of the niord-web project.<br>
 * This is because of a class-loading bug in the Wildfly implementation. See e.g.
 * https://issues.jboss.org/browse/WFLY-4988
 */
@Named
public class BatchDkNmImportReader extends BatchMessageImportReader {

    @Inject
    GeometryFormatService geometryFormatService;

    /** Reads in the batch import messages */
    @Override
    protected List<SystemMessageVo> readMessages() throws Exception {
        // Extract messages from the HTML
        Path path = batchService.getBatchJobDataFile(jobContext.getInstanceId());
        NmHtmlExtractor extractor = new NmHtmlExtractor(path.toFile());

        getLog().info("Parsing NMs for year " + extractor.getYear() +  ", week " + extractor.getWeek());
        List<Message> messages = extractor.extractNms();

        DataFilter dataFilter = DataFilter.get()
                .fields(DataFilter.DETAILS, DataFilter.GEOMETRY, "Area.parent");

        return messages.stream()
                .map(m -> m.toVo(SystemMessageVo.class, dataFilter))
                .map(m -> geometryFormatService.appendGeometryToDetails(m))
                .collect(Collectors.toList());
    }
}
